<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphTo;

class Member extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'guest_id',
        'invited_by_type',
        'invited_by_id',
        'converted_by_user_id',
        'first_name',
        'last_name',
        'email',
        'phone',
        'date_of_birth',
        'gender',
        'status',
        'house_number',
        'street',
        'barangay',
        'city',
        'state',
        'postal_code',
        'country',
    ];

    /**
     * Get the guest this member was converted from (if any).
     */
    public function guest(): BelongsTo
    {
        return $this->belongsTo(Guest::class);
    }

    /**
     * Get the inviter (Coach or Member) who referred this member.
     */
    public function invitedBy(): MorphTo
    {
        return $this->morphTo('invitedBy');
    }

    /**
     * Get the user (staff) who converted this member.
     */
    public function convertedByUser(): BelongsTo
    {
        return $this->belongsTo(User::class, 'converted_by_user_id');
    }

    /**
     * Get the members invited by this member (member's invited_by points to this member).
     */
    public function invitedMembers(): MorphMany
    {
        return $this->morphMany(Member::class, 'invitedBy');
    }

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'date_of_birth' => 'date',
        ];
    }

    /**
     * Get the member's full name.
     */
    public function getFullNameAttribute(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }

    /**
     * Get the RFID cards for the member.
     */
    public function rfidCards(): HasMany
    {
        return $this->hasMany(RfidCard::class);
    }

    /**
     * Get the active RFID card for the member.
     */
    public function activeRfidCard(): HasOne
    {
        return $this->hasOne(RfidCard::class)
            ->where('status', 'active')
            ->where(function ($query) {
                $query->whereNull('expires_at')
                    ->orWhere('expires_at', '>=', now()->toDateString());
            })
            ->latest();
    }

    /**
     * Get the member subscriptions for the member.
     */
    public function memberSubscriptions(): HasMany
    {
        return $this->hasMany(MemberSubscription::class);
    }

    /**
     * Get the active subscription for the member.
     */
    public function activeSubscription(): HasOne
    {
        return $this->hasOne(MemberSubscription::class)
            ->where('status', 'active')
            ->latest();
    }

    /**
     * Get the active member subscription for the member.
     */
    public function activeMemberSubscription(): HasOne
    {
        $today = now()->toDateString();

        return $this->hasOne(MemberSubscription::class)
            ->where('status', 'active')
            ->where('end_date', '>=', $today)
            ->where(function ($query) use ($today) {
                $query->whereNull('frozen_at')
                    ->orWhereNull('frozen_until')
                    ->orWhere('frozen_until', '<', $today)
                    ->orWhere('frozen_at', '>', $today);
            })
            ->latest();
    }

    /**
     * Get the PT session plans for the member.
     */
    public function ptSessionPlans(): HasMany
    {
        return $this->hasMany(PtSessionPlan::class);
    }

    /**
     * Get the access logs for the member.
     */
    public function accessLogs(): HasMany
    {
        return $this->hasMany(AccessLog::class);
    }

    /**
     * Get the guests invited by this member.
     */
    public function invitedGuests(): MorphMany
    {
        return $this->morphMany(Guest::class, 'inviter');
    }

    /**
     * Get the member's PT package subscriptions.
     */
    public function memberPtPackages(): HasMany
    {
        return $this->hasMany(MemberPtPackage::class);
    }

    /**
     * Get the commissions generated by this member's PT packages.
     */
    public function commissions(): HasMany
    {
        return $this->hasMany(Commission::class);
    }

    /**
     * Get the member's active PT package (status active, not past end_date).
     * Check is_active or remaining_sessions for exhaustion.
     */
    public function activeMemberPtPackage(): HasOne
    {
        $today = now()->toDateString();

        return $this->hasOne(MemberPtPackage::class)
            ->where('status', 'active')
            ->where(function ($query) use ($today) {
                $query->whereNull('end_date')->orWhere('end_date', '>=', $today);
            })
            ->latest();
    }
}
